name: V-Processing
main: de.verdox.vprocessing.VProcessing
version: 1.1.3
author: Verdox
website: https://youtube.com/YourServerPromo
database: true
api-version: "1.13"
softdepend: [HolographicDisplays]
commands:
  vproc:
    permission: vproc.admin
  processer: