name: V-Processing
main: de.verdox.vprocessing.VProcessing
version: 1.2.5
authors: [Verdox, to-lutz]
database: true
api-version: "1.20"
depend:
  - HolographicDisplays
commands:
  vproc:
    permission: vproc.admin