name: V-Processing
main: de.verdox.vprocessing.VProcessing
version: 1.0.0
api-version: "1.15"
author: Verdox
commands:
  vproc:
    permission: vproc.admin
    usage: "Usage: /<command> <argument>"
  processer: